title:            An open mind
tagline:          A personal perspective on education, technology and culture
description:      A personal perspective on education, technology and culture
canonical:        https://milesberry.net
title_image:      "https://milesberry.net/images/milesberrynet.png"

# Owner/author information
owner:
  name:           Miles Berry
  avatar:         avatar.png
  bio:            "Professor of Computing Education, University of Roehampton"
  email:          m.berry@roehampton.ac.uk
  twitter:        mberry
  github:         milesberry
  instagram:      mgberry
  disqus:         an-open-mind
  location:       "Godalming, Surrey"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_GB
  title_image:      "https://milesberry.net/images/milesberrynet.png"
  url:              https://milesberry.net 
  description:      "Professor of Computing Education, University of Roehampton"


# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about-3
  - title: Presentations
    url: /presentations
  - title: Publications
    url: /publications
  - title: media
    url: /media-coverage


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
