title:            An open mind
tagline:          A personal perspective on education, technology and culture
description:      A personal perspective on education, technology and culture
canonical:        http://milesberry.github.io

# Owner/author information
owner:
  name:           Miles Berry
  avatar:         avatar.png
  bio:            "Principal lecturer in computing education, University of Roehampton"
  email:          m.berry@roehampton.ac.uk
  twitter:        mberry
  github:         milesberry
  instagram:      mgberry
  disqus:         mgberry
  location:       "Godalming, Surrey"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about-3
  - title: Presentations
    url: /presentations
  - title: Publications
    url: /publications
  - title: media
    url: /media-coverage


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
